---

- name: Install yum-utils
  become: yes
  yum:
    name: yum-utils
    state: present
  tags:
    - install

- name: Enable nginx repo.
  template:
    src: nginx_repo.j2
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify: install updates
  when: nginx_yum_repo_enabled | bool
  tags: 
   - install

- name: yum-config-manager exclude
  shell: yum-config-manager --save --setopt=nginx-stable.skip_if_unavailable=true
  tags:
   - install

- name: Install nginx web server
  yum: name=nginx state=installed update_cache=true
  notify:
    - restart nginx
  tags:
   - install

- name: Copy index.html file
  template:
    src: "{{ index_html_template }}"
    dest: "{{ index_html_file_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  tags:
    - configs

- name: Copy nginx configuration in place.
  template:
    src: "{{ nginx_conf_template }}"
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx
  tags:
    - configs

- name: Make sure a service is running
  systemd:
    state: started
    name: nginx
  tags:
    - install
    - configs
